---
title: "Reprocesamiento de los datos"
---

A partir de la pagina web de Git [proMGE](https://git.embl.de/khedkar/promge) realizamos modificaciones de los scripts para mejorar la documentación de los mismos.

## Datos

> Modificado por: **Evelia Coss**

Todos los datos utilizados en este estudio están publicados y a disposición del público, como se indica en la sección de [material y métodos del manuscrito](https://academic.oup.com/nar/article/50/6/3155/6552054#347997597).

-   Los datos de todos los genomas procariotas utilizados en el estudio están disponibles en https://progenomes.embl.de/.
-   La información sobre el hábitat está disponible en [GMGC](https://gmgc.embl.de/).

![Flujo de trabajo para la identificación de elementos genéticos móviles (MGEs) en procariotas y análisis de carga genética. (A) Se anotaron cinco familias principales de recombinasas en proGenomes2 usando HMMs a nivel de subfamilia y validación con EggNOG y RefSeq. (B) Se asignaron recombinasas a seis categorías de MGEs y se diferenciaron de recombinasas celulares mediante análisis de límites de pangenomas, asociación con subfamilias y la presencia de genes accesorios específicos. (C) Se presentan ejemplos de MGEs con genes de resistencia a antibióticos (ARG), destacando su novedad en aspectos como diversificación funcional, MGEs anidados, transferencia horizontal de genes entre dominios de vida y nuevas asociaciones de dominios proteicos.](img/figure1.jpeg)

## Procesamiento de datos para la Figuras

Los autores nos informan que se realizaron modificacione sobre los inputs para generar las Figuras 2 a 5 empleando codigo de `perl`. Para mas informacion vista la fuente original del [Git](https://git.embl.de/khedkar/promge/-/tree/main?ref_type=heads).
